# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-07 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_field_1', models.BooleanField(default=False)),
                ('a_test_field_2', models.TextField(default='')),
                ('b_test_field_3', models.CharField(max_length=8)),
            ],
        ),
    ]
